### ISSUE TITLE
How to get all fonts in a Pdf file???

### ISSUE THREAD

**Issue by whynozg** [unidoc/unipdf-examples#102]
How to get all fonts in a Pdf file???

**Comment by sampila** [comment]
Hi @whynozg,
UniPDF v3.33.0 now supports extracting fonts in a PDF file. 
The example can be seen here: [https://github.com/unidoc/unipdf-examples/blob/master/extract/pdf_extract_fonts.go](https://github.com/unidoc/unipdf-examples/blob/master/extract/pdf_extract_fonts.go)
