### ISSUE TITLE
Digital signing lags when opening pdf with Adobe Reader

### ISSUE THREAD

**Issue by Duksic** [unidoc/unipdf-examples#106]
I just self signed a document using your library, and it is having problems with Adobe Reader. It loads extremely slow on linux and on windows and OS x it gets stuck or even crashes. Do you know if this is an problem with the unipdf lib or adobe reader?

**Comment by gunnsth** [comment]
@Duksic Please submit the code you are using and files. The information provided here is too vague to be able to provide any information.

**Comment by Duksic** [comment]
@gunnsth i was using this code (pdf_sign_generate_keys.go) to generate keys and sign pdf. The pdf created crashes on start up in adobe reader DC. I managed to sign it using my own .pfx, but using automatic generation resulted in a crash. I sent you pdf that I signed.
[result.pdf](https://github.com/unidoc/unipdf-examples/files/5083808/result.pdf)

**Comment by gunnsth** [comment]
@Duksic Can you attach the original file so we can fully reproduce and analyze?

**Comment by Duksic** [comment]
Here you go @gunnsth 

[testing.pdf](https://github.com/unidoc/unipdf-examples/files/5086661/testing.pdf)
[result.pdf](https://github.com/unidoc/unipdf-examples/files/5086662/result.pdf)

**Comment by adrg** [comment]
Hi @Duksic,

I believe Adobe Reader does not like that the certificate does not have a common name set. Could you try setting one and let us know if it still crashes on Windows and OS X? `BasicConstraintsValid` should be removed as well although it does not seem to cause any issues.

```
template := x509.Certificate{
    SerialNumber: big.NewInt(1),
    Subject: pkix.Name{
        CommonName:   "any",
        Organization: []string{"Test Company"},
    },
    NotBefore: now.Add(-time.Hour),
    NotAfter:  now.Add(time.Hour * 24 * 365),

    KeyUsage:              x509.KeyUsageDigitalSignature,
    ExtKeyUsage:           []x509.ExtKeyUsage{x509.ExtKeyUsageServerAuth},
}
```

Or better yet, a more complete template:
```
template := x509.Certificate{
	SerialNumber: new(big.Int),
	Subject: pkix.Name{
		CommonName:   "any",
		Organization: []string{"Test Company"},
	},
	NotBefore:          now.Add(-time.Hour).UTC(),
	NotAfter:           now.Add(time.Hour * 24 * 365).UTC(),
	PublicKeyAlgorithm: x509.RSA,
	KeyUsage: x509.KeyUsageKeyEncipherment |
		x509.KeyUsageDigitalSignature |
		x509.KeyUsageDataEncipherment,
}
```

**Comment by ahall** [comment]
This sounds like something we should have on help.unidoc.io :)

**Comment by Duksic** [comment]
@adrg  i added that which you mentioned and it worked like a charm, thank you for your assistance ^^

**Comment by Duksic** [comment]
@adrg if i can give you a question, is there a simple way in unipdf to remove digital signatures from pdf?
