### ISSUE TITLE
Generate a page with only image

### ISSUE THREAD

**Issue by victorfernandesraton** [unidoc/unipdf-examples#196]
How to draw image with all size in page?

**Comment by sampila** [comment]
> How to draw image with all size in page?

Hi @victorfernandesraton,
Could you explain more about your use case?

Best regards,
Alip

**Comment by victorfernandesraton** [comment]
I need create pdf from images avaliable in s3 static and dowload the images in local is very unsafe because this behavior depends of filesystem and i need manage local temp folders

I suposed wich is a way to using bytes buffering for add image insteread to find on filesystem

**Comment by sampila** [comment]
Hi @victorfernandesraton,

Yes, you can add the image to pdf using bytes with `creator.NewImageFromData(bytes []byte)`.
More detail about it [https://apidocs.unidoc.io/unipdf/v3.37.0/github.com/unidoc/unipdf/v3/creator/#Creator.NewImageFromData](https://apidocs.unidoc.io/unipdf/v3.37.0/github.com/unidoc/unipdf/v3/creator/#Creator.NewImageFromData)
Hope this help.

Best regards,
Alip

**Comment by victorfernandesraton** [comment]
sure i'll try this. Thanks

**Comment by sampila** [comment]
We closing this issue, you can re-open this issue if you have an issue regarding this.
