### ISSUE TITLE
Page Numbering Mismatch

### ISSUE THREAD

**Issue by ikeadeoyin** [unidoc/unipdf-examples#199]
The page number in the input PDF and the output of the [extract_text_bound](https://github.com/unidoc/unipdf-examples/blob/master/extract/extract_text_bound.go) example doesn't match.

**Comment by gunnsth** [comment]
@ikeadeoyin Can you provide steps to reproduce and a test file?  Is the difference just +1 (like index number vs index number + 1) or completely different?

**Comment by gunnsth** [comment]
Unable to reproduce
