### ISSUE TITLE
TestAppenderSignMultiple not work well yet 

### ISSUE THREAD

**Issue by sayhei** [unidoc/unipdf-examples#41]
i have try the example of the test method  in model  appender_test.go file,and only the fist file is well,can you check it ?

**Comment by gunnsth** [comment]
Please post the full code snippet and specific errors that can be reproduced.

**Comment by sayhei** [comment]
-------------------- code -------------------
func main()  {
	inputPath := testPdfLoremIpsumFile

	for i := 0; i < 3; i++ {
		f, err := os.Open(inputPath)
		if err != nil {
			fmt.Println("Fail: %v\n", err)
			return
		}

		pdfReader, err := model.NewPdfReader(f)
		if err != nil {
			fmt.Println("Fail: %v\n", err)
			f.Close()
			return
		}

		fmt.Println("Fields: %d", len(pdfReader.AcroForm.AllFields()))

		if len(pdfReader.AcroForm.AllFields()) != i {
			fmt.Println("fields != %d (got %d)", i, len(pdfReader.AcroForm.AllFields()))
		}

		annotations, err := pdfReader.PageList[0].GetAnnotations()
		//require.NoError(t, err)
		fmt.Println("Annotations: %d", len(annotations))
		if len(annotations) != i {
			fmt.Println("page annotations != %d (got %d)", i, len(annotations))
		}

		appender, err := model.NewPdfAppender(pdfReader)
		if err != nil {
			fmt.Println("Fail: %v\n", err)
			f.Close()
			return
		}

		pfxData, _ := ioutil.ReadFile(testPKS12Key)
		privateKey, cert, err := pkcs12.Decode(pfxData, testPKS12KeyPassword)
		if err != nil {
			fmt.Println("Fail: %v\n", err)
			f.Close()
			return
		}

		handler, err := sighandler.NewAdobePKCS7Detached(privateKey.(*rsa.PrivateKey), cert)
		if err != nil {
			fmt.Println("Fail: %v\n", err)
			f.Close()
			return
		}

		// Create signature field and appearance.
		signature := model.NewPdfSignature(handler)
		signature.SetName(fmt.Sprintf("Test Appender - Round %d", i+1))
		signature.SetReason(fmt.Sprintf("Test Appender - Round %d", i+1))
		signature.SetDate(time.Now(), "")

		if err := signature.Initialize(); err != nil {
			return
		}

		sigField := model.NewPdfFieldSignature(signature)
		sigField.T = core.MakeString(fmt.Sprintf("Signature %d", i+1))
		sigField.Rect = core.MakeArray(
			core.MakeInteger(0),
			core.MakeInteger(0),
			core.MakeInteger(0),
			core.MakeInteger(0),
		)

		if err = appender.Sign(1, sigField); err != nil {
			fmt.Println("Fail: %v\n", err)
			f.Close()
			return
		}

		outPath := tempFile(fmt.Sprintf("appender_sign_multiple_%d.pdf", i+1))

		err = appender.WriteToFile(outPath)
		if err != nil {
			fmt.Println("Fail: %v\n", err)
			f.Close()
			return
		}

		validateFile(outPath)
		inputPath = outPath

		f.Close()
	}

}

func validateFile(fileName string) {
	fmt.Println("Validating %s", fileName)
	data, err := ioutil.ReadFile(fileName)
	if err != nil {
		fmt.Println("Fail: %v\n", err)
		return
	}
	reader, err := model.NewPdfReader(bytes.NewReader(data))
	if err != nil {
		fmt.Println("Fail: %v\n", err)
		return
	}

	handler, _ := sighandler.NewAdobeX509RSASHA1(nil, nil)
	handler2, _ := sighandler.NewAdobePKCS7Detached(nil, nil)
	handlers := []model.SignatureHandler{handler, handler2}

	res, err := reader.ValidateSignatures(handlers)
	if err != nil {
		fmt.Println("Fail: %v\n", err)
		return
	}
	if len(res) == 0 {
		fmt.Println("Fail: signature fields not found")
		return
	}

	if !res[0].IsSigned || !res[0].IsVerified {
		fmt.Println("Fail: validation failed")
		return
	}

	for i, item := range res {
		fmt.Println("== Signature %d", i+1)
		fmt.Println("%s", item.String())
	}
}
-------------------- screenshot -------------------
![1](https://user-images.githubusercontent.com/8320880/56545395-0f79d880-65aa-11e9-970d-74fef5b1af63.png)
![2](https://user-images.githubusercontent.com/8320880/56545418-1ef92180-65aa-11e9-9b1a-856a374c5e04.png)
![3](https://user-images.githubusercontent.com/8320880/56545424-23253f00-65aa-11e9-84fa-d04c7b05e8d7.png)

i use this code generate 3files names appender_sign_multiple_1.pdf,appender_sign_multiple_2.pdf,appender_sign_multiple_3.pdf.
when i open them with Adobe Acrobat Reader DB , only the first one looks like a whole, appender_sign_multiple_2.pdf file only see signature2 and prompt me that at least one signature is invalid. appender_sign_multiple_3.pdf only see Signature 3.

**Comment by gunnsth** [comment]
@sayhei this has been fixed
