### ISSUE TITLE
JSON format for fjson.LoadFromJSONFile

### ISSUE THREAD

**Issue by FourShore** [unidoc/unipdf-examples#49]
What format does the JSON need to be in to fill a pdf form?

[
{
    "name": "KEY",
    "value": "VALUE"
}
...
]

??

**Comment by FourShore** [comment]
I think I figured it out. I can get data from

fieldData, err := fjson.LoadFromJSON(bytes.NewReader(jsonData))
fmt.Println("fieldData", fieldData)

to print

&{[{TradeYear 2030 []} {TradeColor Black []} {BuyerName Erin Vidimçe's []} {Today 6/13/2019 []} {TradeNetValue $10,000,000 []} {TradeVIN VIN123456 []} {TradeMake Lambo []} {TradeOdometer 14,000 mi []} {TradeTrim Classic []} {TradeModel Truck []}]}

but output pdf does not get populated.

Here's the rest of my code after the data:

`// Populate the form data.
	err = pdfReader.AcroForm.Fill(fieldData)
	if err != nil {
		return err
	}

	// Flatten form.
	fieldAppearance := annotator.FieldAppearance{OnlyIfMissing: true, RegenerateTextFields: true}

	err = pdfReader.FlattenFields(true, fieldAppearance)
	if err != nil {
		return err
	}

	// Write out.
	pdfWriter := model.NewPdfWriter()
	pdfWriter.SetForms(nil)

	for _, p := range pdfReader.PageList {
		err := pdfWriter.AddPage(p)
		if err != nil {
			return err
		}
	}

	fout, err := os.Create(outputPath)
	if err != nil {
		return err
	}
	defer fout.Close()

	err = pdfWriter.Write(fout)
	return err`

**Comment by FourShore** [comment]
## UPDATE ##

I am able to fill the form by adding a print statement after pdfReader.AcroForm.Fill(fieldData)

`
fmt.Println("After: All Fields", pdfReader.AcroForm.AllFields())
fmt.Println()
`

This seems very strange but if I literally comment in/out these two lines the form goes from filled to not filled. I thought maybe there is a race condition somewhere but when I tried time.Sleep(2 * time.Second) this does not work. The form is empty.

Another thing to note is though the form is filled it is not flattened.

**Comment by adrg** [comment]
Hi @FourShore 

Thank you for reporting the problem. Can you try using the branch in PR #93 (https://github.com/unidoc/unipdf/pull/93) and see if that solves the issue for you?

**Comment by FourShore** [comment]
How do I use go dep ensure with this library? I get reference errors requiring routes with .../v3/...

**Comment by adrg** [comment]
go dep seems to have some active issues which are producing those errors. Could you use go modules instead?
