### ISSUE TITLE
Location in digital signature

### ISSUE THREAD

**Issue by palhov-roman** [unidoc/unipdf-examples#61]
I try run example [pdf_sign_appearance.go](https://github.com/unidoc/unipdf-examples/blob/v3/signatures/pdf_sign_appearance.go) with Location parameter:
`signature.SetLocation("Brookline, MA")`
In result document I see Reason field, but don't see Location field

**Comment by adrg** [comment]
@palhov-roman The `SetReason` and `SetLocation` are used only to set the `Reason` and `Location` fields of the signature dictionary. They do not affect the appearance of the signature.

The appearance of the signature can be configured using the `annotator` package as done in the example you mentioned starting with [line 89](https://github.com/unidoc/unipdf-examples/blob/v3/signatures/pdf_sign_appearance.go#L89).

You can show the fields in the signature appearance by doing something like this:
```
signature.SetReason("Some reason")
signature.SetLocation("Brookline, MA")

opts := annotator.NewSignatureFieldOpts()
// the font size of the signature lines.
opts.FontSize = 10
// the location and size of the signature appearance rectangle.
opts.Rect = []float64{10, 25, 75, 60}

sigField, err := annotator.NewSignatureField(
    signature,
    []*annotator.SignatureLine{
        // Reason: Some reason
        annotator.NewSignatureLine("Reason",signature.Reason.String()),    
        // Location: Brookline, MA
        annotator.NewSignatureLine("Location", signature.Location.String()),
        // ...
        // any other lines you would like to add to the signature appearance.
        // ...
    },
    opts,
)
```

If you don't want to show the label of the signature line, you can pass an empty string as the first parameter to `NewSignatureLine`:
```
// Brookline, MA
// instead of:
// Location: Brookline, MA
annotator.NewSignatureLine("", signature.Location.String()),
```

This way, the user can choose what is shown in the signature appearance annotation.
