### ISSUE TITLE
[Question] Underline

### ISSUE THREAD

**Issue by polderudo** [unidoc/unipdf-examples#66]
Is there any example on how to underline text in a PDF?

**Comment by gunnsth** [comment]
@polderudo At the moment it is not possible.  Surprisingly underlining text in PDF is not as trivial as it sounds.  One needs to track positions and actually draw lines under the text.

We do have a feature request for this: https://github.com/unidoc/unipdf/issues/184
We do have everything that is needed to do this, I believe, so I expect we will implement this soon.

**Comment by polderudo** [comment]
Ok. Then waiting for this
