### ISSUE TITLE
Advanced search/replace issue

### ISSUE THREAD

**Issue by virtuald** [unidoc/unipdf-examples#79]
First, this example was a more elegant solution to the problem as I described in https://github.com/unidoc/unipdf/issues/267 . Thank you!

For the documents I'm interested in, here are some attributes from them since I can't share the originals nor can I create my own documents:

* Created with Adobe PDF Library 9.0
* Acrobat PDFMaker 9.0 for Word
* PDF 1.5
* Optimized

The advanced search/replace *almost* works, which is great.

The problem I have is that my letters are segmented to an individual letter per text object, which means this example puts all of the text in the first object, and sets all the other objects to empty. Unfortunately, my pdf viewer moves all the text over to the left, so the new text overlaps with the text next to the old text by quite a bit. Not good.

The solution is to walk each text segment, and in each segment replace the existing characters with the corresponding characters from the replacement text. There are some visible problems when the search text is larger than the replace text, but it's pretty good otherwise.

I've created a modified version of the example, but it was pretty straightforward to do and I don't want to sign the CLA at this time. The fix involves rewriting the inner loop of the 'replace' function, and just modifying the way that you change the chunks. Psuedocode is as follows:

```

// loop 1
  // loop 2
    // loop 3
      .. existing 'continue' code
      // chunkOffset += 1

      // keep track of consumed characters

      // chunkoffset loop
        // ensure the first chunk retains some of the original content

        // middle chunks: replace all of this chunks content, increment chunkOffset

        // last chunk: append any remaining content
```

**Comment by gunnsth** [comment]
@virtuald Thanks. Unfortunately I am not sure it will be easy to implement this without any test materials, but we will keep it in mind if we run into similar sounding problems in the future.
