### ISSUE TITLE
Error version not found

### ISSUE THREAD

**Issue by hg-pooraa** [unidoc/unipdf-examples#90]
https://github.com/unidoc/unipdf-examples/blob/7caf25626fde1a8ca6bafbcb93fb9bedac504371/image/pdf_watermark_image.go#L41
Error :version not found
unable to resolve this issue

**Comment by gunnsth** [comment]
Please attach all files needed to reproduce the issue.

**Comment by gunnsth** [comment]
Closing as missing information to reproduce.
