### ISSUE TITLE
Replaced text looks incorrect

### ISSUE THREAD

**Issue by gunnsth** [unidoc/unipdf-examples#95]
An issue was received via email.

> About text replacement I checked it with our document. The searched text is replaced but some symbols displayed incorrect. For example I try to replace word TYPE with A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y, Z and symbols J, K, V and Y does not displayed. Instead of this symbols I received empty space. The same case with lower case. Also all special symbols displayed incorrect !@#$%^&*(){}_-+=[]

This applies to the advanced text replacement example.
An example PDF template was provided.

**Comment by gunnsth** [comment]
@adrg I think this has already been fixed?  Should be able to close

**Comment by DeadNumbers** [comment]
@gunnsth no, this is not fixed 
![изображение](https://user-images.githubusercontent.com/9416005/85724010-51893780-b6e3-11ea-8fff-476368539073.png)
